spring.application.name=service_user
spring.datasource.url=jdbc:mysql://localhost:3306/microservice_exercice
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=root
spring.datasource.password=root