FROM nginx

LABEL version="0.1"

RUN apt update -y && apt upgrade -y && apt install git -y

WORKDIR /usr/share/nginx/html

RUN git clone https://github.com/withaarzoo/3D-Rotate-Tube.git && mv 3D-Rotate-Tube/* .

EXPOSE 80

CMD ["nginx","-g","daemon off;"]